# Brewfile

brew "zsh"
brew "git"
brew "node"
brew "python"
cask "warp"
cask "google-chrome"
cask "visual-studio-code"
cask "spotify"
cask "raycast"
cask "linear-linear"
cask "firefox"
cask "zoom"
cask "sublime-text"