# https://taskfile.dev
version: '3'

vars:
  DOTFILES_DIR: '{{.ROOT_DIR}}/dotfiles'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ===========================================================================
  # MAIN TASKS
  # ===========================================================================

  all:
    desc: Run full setup (brew, dotfiles, git, claude)
    cmds:
      - task: brew
      - task: dotfiles
      - task: zsh-plugins
      - task: git
      - task: claude

  # ===========================================================================
  # HOMEBREW
  # ===========================================================================

  brew:
    desc: Install Homebrew and all packages from Brewfile
    cmds:
      - task: brew:install
      - task: brew:bundle
      - task: brew:cleanup

  brew:install:
    desc: Install Homebrew if not present
    status:
      - command -v brew
    cmds:
      - echo "Installing Homebrew..."
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - |
        if [[ $(uname -m) == "arm64" ]]; then
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"
        fi

  brew:bundle:
    desc: Install packages from Brewfile
    cmds:
      - brew update
      - brew upgrade
      - brew bundle --file {{.ROOT_DIR}}/Brewfile

  brew:cleanup:
    desc: Remove packages not in Brewfile
    cmds:
      - brew bundle cleanup --force --file {{.ROOT_DIR}}/Brewfile
      - brew bundle check --file {{.ROOT_DIR}}/Brewfile

  brew:dump:
    desc: Export current brew packages to Brewfile (use with caution)
    cmds:
      - brew bundle dump --force --file {{.ROOT_DIR}}/Brewfile
      - "echo 'Warning: Review Brewfile - may contain transitive dependencies'"

  brew:lock:
    desc: Update Brewfile.lock.json
    cmds:
      - brew bundle lock --file {{.ROOT_DIR}}/Brewfile

  # ===========================================================================
  # DOTFILES
  # ===========================================================================

  dotfiles:
    desc: Symlink all dotfiles to home directory
    cmds:
      - task: dotfiles:zsh
      - task: dotfiles:zed

  dotfiles:zsh:
    desc: Symlink zsh configuration
    cmds:
      - |
        if [ -f ~/.zshrc ] && [ ! -L ~/.zshrc ]; then
          echo "Backing up existing .zshrc to .zshrc.backup"
          mv ~/.zshrc ~/.zshrc.backup
        fi
      - ln -sf {{.DOTFILES_DIR}}/zsh/zshrc ~/.zshrc
      - ln -sf {{.DOTFILES_DIR}}/zsh/p10k.zsh ~/.p10k.zsh
      - echo "Symlinked zsh config"

  dotfiles:zed:
    desc: Symlink Zed configuration
    cmds:
      - mkdir -p ~/.config/zed
      - |
        if [ -f ~/.config/zed/settings.json ] && [ ! -L ~/.config/zed/settings.json ]; then
          echo "Backing up existing Zed settings"
          mv ~/.config/zed/settings.json ~/.config/zed/settings.json.backup
        fi
      - ln -sf {{.DOTFILES_DIR}}/zed/settings.json ~/.config/zed/settings.json
      - echo "Symlinked Zed config"

  dotfiles:backup:
    desc: Copy current dotfiles from system to this repo
    cmds:
      - cp ~/.zshrc {{.DOTFILES_DIR}}/zsh/zshrc
      - cp ~/.p10k.zsh {{.DOTFILES_DIR}}/zsh/p10k.zsh
      - cp ~/.config/zed/settings.json {{.DOTFILES_DIR}}/zed/settings.json
      - echo "Dotfiles backed up to repo"

  # ===========================================================================
  # ZSH PLUGINS (not managed by Homebrew)
  # ===========================================================================

  zsh-plugins:
    desc: Install oh-my-zsh and plugins
    cmds:
      - task: zsh-plugins:omz
      - task: zsh-plugins:p10k
      - task: zsh-plugins:autosuggestions
      - task: zsh-plugins:syntax-highlighting

  zsh-plugins:omz:
    desc: Install oh-my-zsh
    status:
      - test -d ~/.oh-my-zsh
    cmds:
      - echo "Installing oh-my-zsh..."
      - sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

  zsh-plugins:p10k:
    desc: Install powerlevel10k theme
    status:
      - test -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
    cmds:
      - echo "Installing powerlevel10k..."
      - git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

  zsh-plugins:autosuggestions:
    desc: Install zsh-autosuggestions
    status:
      - test -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    cmds:
      - echo "Installing zsh-autosuggestions..."
      - git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

  zsh-plugins:syntax-highlighting:
    desc: Install zsh-syntax-highlighting
    status:
      - test -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
    cmds:
      - echo "Installing zsh-syntax-highlighting..."
      - git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

  # ===========================================================================
  # GIT
  # ===========================================================================

  git:
    desc: Configure git globally
    cmds:
      - git config --global user.name "Saadat Qadri"
      - git config --global user.email "saadat.qadri@gmail.com"
      - git config --global init.defaultBranch main
      - git config --global core.editor "zed --wait"
      - git config --global credential.helper cache
      - git config --global user.signingkey 3CD5D6A0B9B8F207
      - git config --global commit.gpgsign true
      - echo "Git configured"

  # ===========================================================================
  # CLAUDE CODE
  # ===========================================================================

  claude:
    desc: Install or update Claude Code
    cmds:
      - |
        if ! command -v claude &> /dev/null; then
          echo "Installing Claude Code..."
          npm install -g @anthropic-ai/claude-code
        else
          echo "Updating Claude Code..."
          npm update -g @anthropic-ai/claude-code
        fi
      - echo "Claude Code ready. Run 'claude' to authenticate."

  # ===========================================================================
  # UTILITIES
  # ===========================================================================

  status:
    desc: Show current setup status
    cmds:
      - echo "=== Setup Status ==="
      - echo ""
      - echo "Homebrew:"
      - brew bundle check --file {{.ROOT_DIR}}/Brewfile || true
      - echo ""
      - echo "Dotfiles:"
      - |
        [ -L ~/.zshrc ] && echo "  ~/.zshrc -> $(readlink ~/.zshrc)" || echo "  ~/.zshrc: not symlinked"
        [ -L ~/.p10k.zsh ] && echo "  ~/.p10k.zsh -> $(readlink ~/.p10k.zsh)" || echo "  ~/.p10k.zsh: not symlinked"
        [ -L ~/.config/zed/settings.json ] && echo "  ~/.config/zed/settings.json -> $(readlink ~/.config/zed/settings.json)" || echo "  ~/.config/zed/settings.json: not symlinked"
      - echo ""
      - echo "Tools:"
      - |
        command -v claude &> /dev/null && echo "  Claude Code: $(claude --version 2>/dev/null || echo 'installed')" || echo "  Claude Code: not installed"
        command -v node &> /dev/null && echo "  Node: $(node --version)" || echo "  Node: not installed"
        command -v uv &> /dev/null && echo "  uv: $(uv --version)" || echo "  uv: not installed"
